### ISSUE TITLE
unneccessary url encoding results in 405 for get

### ISSUE THREAD

**Issue by codygman** [svanderburg/node2nix#172]
I'm using `node2nix 1.7.0` on `nixos-20.03pre211190.a21c2fa3ea2`.

I have a dependency in the format of:

```
npm install @company-organization/company-repo-1
```

It's failing like this:

```
[cody@nixos:~/project/assets]$ node2nix 
fetching local directory: ./. from .
info attempt registry request try #1 at 4:18:12 PM
http request GET https://registry.npmjs.org/@company-organization%2Fcompany-project-1
http 404 https://registry.npmjs.org/@company-organization%2Fcompany-project-1
Error: Not found : @company-organization/company-project-1
```

I have an NPM_TOKEN set in my environment and I verified doing the npm install at the beginning works in the same terminal I got the error in.

**Comment by svanderburg** [comment]
I believe: `@company-organization/company-repo-1` is just a place holder for a scoped package, right? Scoped packages should be supported.

A question: is this package that you intend to deploy coming from a private registry? I just merged a pull request b949c2abc6d41ba35856c23aa9f1d1c539c66778 that adds a new command-line option to configure a token.

Can you give it a try and see if this solves your problem? You should install the development version. You can find how to deploy it with Nix in the README.md file.

**Comment by christian-blades-cb** [comment]
@svanderburg I have a similar issue, trying to use that new `--registry-auth-token` flag, and I still get the 404's when I build.

Should I see the auth token being persisted to one of the files? I don't see any difference with or without that flag.

Here's how I'm invoking node2nix, for reference:
```bash
#!/usr/bin/env nix-shell
#!nix-shell -i bash -p gawk
# shellcheck shell=bash

set -eu -o pipefail

npmtoken=$(gawk 'match($0, /authToken=(.*)/, a) { print a[1] }' .npmrc)

node2nix -l package-lock.json --nodejs-10 -c composition.nix --registry-auth-token "${npmtoken}"
```

```
❯ node2nix -v
node2nix 1.8.0
```

**Comment by christian-blades-cb** [comment]
I have a workaround for the above, basically just injecting the token from npmrc into a header via curlOpts.

```nix
{ sources ? import ./nix/sources.nix,
  system ? builtins.currentSystem,
  pkgs ? import sources.nixpkgs { inherit system; }
}:

let
  # extract the auth token from npmrc
  auth_header = let
    npmrc = builtins.readFile ./.npmrc;
    token = builtins.head (builtins.match ".*_authToken=(.+)" npmrc);
  in "Authorization: Bearer ${token}";

  # force node2nix to fetch packages with our bearer token
  overlay = self: super: {
    fetchurl = opts: super.fetchurl (opts // {
      curlOpts = with super.lib; (toList (opts.curlOpts or [])) ++ [ "--header" auth_header ];
    });
  };

  nodeEnv = import ./composition.nix {
    pkgs = import sources.nixpkgs { inherit system; overlays = [ overlay ]; };
  };
in nodeEnv
```

**Comment by svanderburg** [comment]
Ah I guess the registry returns a 404 error in case the authorization does not work. I'll have a look at the solution shown above and see how we can expose this as a feature in `node2nix`.

**Comment by codygman** [comment]
Just checked, still affected by this. I was also trying to get the above solution working. I guess I could use this default.nix:

```nix
{pkgs ? import <nixpkgs> {
  inherit system;
}, system ? builtins.currentSystem}:
let
  # extract the auth token from npmrc
  auth_header ="Authorization: Bearer ${NPM_TOKEN}";

  # force node2nix to fetch packages with our bearer token
  overlay = self: super: {
    fetchurl = opts: throw "we overrode it!"; # Not working, test that fetchurl overriden
    # fetchurl = opts: super.fetchurl (opts // {
    #   curlOpts = with super.lib; (toList (opts.curlOpts or [])) ++ [ "--header" auth_header ];
    # });
  };

  nodeEnv =  {
    pkgs = import <nixpkgs> { inherit system; overlays = [ overlay ]; };
  };
in nodeEnv

```

But node2nix doesn't seem to throw the error to verify it works. I first tried the actual override of course and it gave the original 404.

**Comment by codygman** [comment]
I tried again and more througly documented my attempt at implementing @christian-blades-cb's workaround but couldn't get it working. I also looked through your repos for complete examples to see if I could find what I might be missing or doing wrong, but couldn't find any.

Here is my attempt:


# export npm token


# do curl to prove I have correct npm token

```sh
curl -I https://registry.npmjs.org/@myorg%2fmy-api --header "Authorization: Bearer ${NPM_TOKEN}" | head -n 4
```

    HTTP/2 200 
    date: Thu, 16 Jul 2020 21:13:10 GMT
    content-type: application/octet-stream
    content-length: 18153


# Show my default.nix

```sh
cat default.nix
```

    {pkgs ? import <nixpkgs> {
      inherit system;
    }, system ? builtins.currentSystem}:
    let
      NPM_TOKEN = pkgs.getEnv "NPM_TOKEN";
      auth_header ="Authorization: Bearer ${NPM_TOKEN}";
    
      overlay = self: super: {
        fetchurl = opts: super.fetchurl (opts // {
          curlOpts = with super.lib;
    	(toList (opts.curlOpts or [])) ++
    	(builtins.trace "adding custom header to fetchurl" [ "--header" auth_header ]);
        });
      };
    
      nodeEnv =  {
        pkgs = import <nixpkgs> { inherit system; overlays = [ overlay ]; };
      };
    
    in nodeEnv


# try running node2nix

```sh
exec 2>&1
node2nix
:
```

    fetching local directory: ./. from .
    info attempt registry request try #1 at 4:13:10 PM
    http request GET https://registry.npmjs.org/@myorg%2Fmy-api
    http 404 https://registry.npmjs.org/@myorg%2Fmy-api
    Error: Not found : @myorgmy-api

**Comment by codygman** [comment]
I clearly didn't read the docs well enough, didn't notice this, or it was recently implemented. This works fine for me:

```shell
[cody@nixos:~/itprotv-api]$ node2nix  --registry-auth-token $NPM_TOKEN
```

Thank you all.

**Comment by codygman** [comment]
So, calling nix-build on this requires an ugly workaround:

```nix
# override.nix (called with nix-build override.nix)
{pkgs ? import <nixpkgs> {
    inherit system;
}, system ? builtins.currentSystem}:

let
  nodePackages = import ./default.nix {
    pkgs = import <nixpkgs> { inherit system; overlays = [ overlay ]; };
  };
  # force node2nix to fetch packages with our bearer token
  overlay = self: super: {
    fetchurl = opts: super.fetchurl (opts // {
      curlOpts = with super.lib; (toList (opts.curlOpts or [])) ++ [ "--header @${pkgs.writeText "headers.txt" "Authorization: Bearer my-token-here"}" ];

    });
  };

in nodePackages 
```

Reopening this just in case you want to add that to the documentation.

**Comment by Larusso** [comment]
Thanks @codygman for your last commend. I was working through this today and your workaround fixed it for me. I was wondering why `node2nix` has the token option but installation still fails ;).

**Comment by codygman** [comment]
> Thanks @codygman for your last commend. I was working through this today and your workaround fixed it for me. I was wondering why `node2nix` has the token option but installation still fails ;).

I'm constantly frustrated after landing on an "almost works" snippet of code after hours of research but are out of energy to pull all of the constiuent pieces of context together...

that's what led me to (and gave me the extra energy to) make sure I posted my minimal working example :smile:

**Comment by Larusso** [comment]
@codygman I feel you. My initial joy was also shortlived because in my case the build failed in the end because of some `gyp` not found yada yada issues. I dropped it there for now :(

**Comment by benley** [comment]
Another year has passed.  Is @codygman's method in https://github.com/svanderburg/node2nix/issues/172#issuecomment-659728902 still the best option for accessing private packages?  I'm glad to have it working, but it would be super nice to have a fix added to node2nix itself at some point - or at least its documentation.
